server:
  port: 8088

spring:
  application:
    name: mall-gateway
  main:
    web-application-type: reactive
  profiles:
    active: dev #默认为开发环境
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# jwt, secure(动态白名单) 以及 gateway routes 均已在 mall-common-dev.yaml 和 mall-gateway-dev.yaml 中配置